# Generated by Django 5.0.1 on 2024-01-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0003_category_lead_converted_date_lead_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leads.userprofile'),
        ),
    ]
